package com.lumabeat.app.audio

enum class BeatPreset(
    val label: String,
    val description: String,
    val baselineBrightness: Int,
    val peakBrightness: Int,
    val pulseDurationMillis: Long,
    internal val bassThreshold: Double,
    internal val generalThreshold: Double,
    internal val generalWeight: Double,
    internal val hitGate: Float,
    internal val minimumHitLevel: Float,
    internal val releaseMultiplier: Float,
    internal val cooldownFrames: Int,
) {
    SUAVE(
        label = "Soft",
        description = "Wide, relaxed brightness changes",
        baselineBrightness = 32,
        peakBrightness = 76,
        pulseDurationMillis = 180,
        bassThreshold = 1.65,
        generalThreshold = 1.90,
        generalWeight = 0.34,
        hitGate = 0.28f,
        minimumHitLevel = 0.55f,
        releaseMultiplier = 0.66f,
        cooldownFrames = 4,
    ),
    MARCADO(
        label = "Punchy",
        description = "Prioritizes kick and percussion",
        baselineBrightness = 18,
        peakBrightness = 94,
        pulseDurationMillis = 140,
        bassThreshold = 1.38,
        generalThreshold = 1.62,
        generalWeight = 0.44,
        hitGate = 0.20f,
        minimumHitLevel = 0.70f,
        releaseMultiplier = 0.46f,
        cooldownFrames = 3,
    ),
    INTENSO(
        label = "Intense",
        description = "Fast flashes on strong hits",
        baselineBrightness = 10,
        peakBrightness = 100,
        pulseDurationMillis = 110,
        bassThreshold = 1.20,
        generalThreshold = 1.42,
        generalWeight = 0.52,
        hitGate = 0.14f,
        minimumHitLevel = 0.80f,
        releaseMultiplier = 0.32f,
        cooldownFrames = 2,
    ),
}
